volumes:
  marketplace_db_data:

services:
  marketplace_database:
    image: postgres:alpine
    container_name: marketplace_database
    restart: unless-stopped
    volumes:
      - ./infrastructure/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - marketplace_db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    expose:
      - 5432
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      SCHEMA: public
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    image: alex2342/marketplace_web:latest
    container_name: marketplace_web
    restart: unless-stopped
    command: python /app/manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - .env
    environment:
      DB_HOST: marketplace_database
      DB_PORT: 5432
      DB_NAME: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - marketplace_database