# Volumes
volumes:
  marketplace_db_data:

services:

  # Postgres
  marketplace_database:
    image: postgres:alpine
    container_name: marketplace_database
    restart: unless-stopped
    volumes:
      - ./infrastructure/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - marketplace_db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    expose:
      - 5432
    env_file:
      - backend_api/.env
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      SCHEMA: public
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}" ]
      interval: 10s
      timeout: 5s
      retries: 5
