# Generated by Django 5.1.7 on 2025-06-20 17:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(default='s', max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_name', message="Ім'я та прізвище можуть містити лише кирилицю, латиницю, дефіс (не на початку чи в кінці).", regex='^(?!-)([A-Za-zА-Яа-яїЇіІєЄґҐ]+)(?<!-)$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_name', message="Ім'я та прізвище можуть містити лише кирилицю, латиницю, дефіс (не на початку чи в кінці).", regex='^(?!-)([A-Za-zА-Яа-яїЇіІєЄґҐ]+)(?<!-)$')]),
        ),
    ]
