# Generated by Django 5.1.7 on 2025-06-21 20:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_verification_token_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_name', message="Ім'я та прізвище можуть містити лише кирилицю, латиницю, дефіс (не на початку чи в кінці).", regex='^(?!-)([A-Za-zА-Яа-яїЇіІєЄґҐ]+)(?<!-)$')]),
        ),
    ]
