# Generated by Django 5.1.7 on 2025-04-20 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_order_updated_at_product_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
