# Generated by Django 5.1.7 on 2025-06-25 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_emaillog'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
