# Generated by Django 5.1.7 on 2025-06-16 14:30

import django.contrib.postgres.fields
from django.db import migrations, models

def migrate_to_roles(apps, schema_editor):
    User = apps.get_model('core', 'User')
    Group = apps.get_model('auth', 'Group')
    for user in User.objects.all():
        # Якщо користувач має групу Admins, додаємо роль 'admin'
        if user.groups.filter(name='Admins').exists():
            user.roles = ['admin']
        else:
            # Переносимо role у roles, замінюючи 'customer' або 'vendor' на 'user'
            if user.role in ['customer', 'vendor']:
                user.roles = ['user']
            elif user.role == 'admin':
                user.roles = ['admin']
            else:
                user.roles = ['user']  # За замовчуванням
        user.save()

def reverse_migrate_to_roles(apps, schema_editor):
    User = apps.get_model('core', 'User')
    Group = apps.get_model('auth', 'Group')
    for user in User.objects.all():
        # Зворотне перенесення: беремо першу роль із roles
        if user.roles:
            if user.roles[0] == 'user':
                user.role = 'customer'  # Або 'vendor', залежно від логіки
            elif user.roles[0] == 'admin':
                user.role = 'admin'
                # Додаємо групу Admins для зворотної сумісності
                admin_group, _ = Group.objects.get_or_create(name='Admins')
                user.groups.add(admin_group)
        else:
            user.role = 'customer'
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0007_auto_20250616_1230'),
    ]

    operations = [
        # Додаємо поле roles
        migrations.AddField(
            model_name='user',
            name='roles',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], max_length=10),
                blank=True,
                db_index=True,
                default=list,
                size=None,
            ),
        ),
        # Переносимо дані
        migrations.RunPython(migrate_to_roles, reverse_migrate_to_roles),
        # Видаляємо поле role
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        # Видаляємо зв’язок із groups
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        # Видаляємо зв’язок із user_permissions
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
    ]