# Generated by Django 5.1.7 on 2025-06-19 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_user_role_user_roles_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='verification_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verification_expires_at',
        ),
    ]
