# Generated by Django 5.1.7 on 2025-06-30 18:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_product_discount_price_product_rating_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=255, validators=[django.core.validators.RegexValidator(code='invalid_product_name', message='Назва продукту може містити літери, цифри, пробіли, дефіси та одинарні лапки.', regex="^[A-Za-zА-Яа-я0-9\\s\\-\\']+$")]),
        ),
    ]
