# Generated by Django 5.1.7 on 2025-07-03 16:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.URLField(blank=True, null=True)),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_product_name', message='Назва продукту може містити літери, цифри, пробіли, дефіси та одинарні лапки.', regex="^[A-Za-zА-Яа-я0-9\\s\\-\\']+$")])),
                ('surname', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_product_name', message='Назва продукту може містити літери, цифри, пробіли, дефіси та одинарні лапки.', regex="^[A-Za-zА-Яа-я0-9\\s\\-\\']+$")])),
                ('city', models.CharField(max_length=100)),
                ('rating', models.IntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('review_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
