name: Pull Request Check

on:
  pull_request:
    branches:
      - main

env:
  USE_SQLITE: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: action/srtup-python@v5
        with:
          python-version: "3.13"
          
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Check code style
        run: flake8
        
      - name: Run migrations
        run: python manage.py migrate
        
      - name: Run tests
        run: coverage run manage.py test
