name: Pull Request Check

on:
  pull_request:
    branches:
      - main

env:
  USE_SQLITE: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.12", "3.13"]

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Install dependencies
        working-directory: ./backend_api
        run: |
          python -m pip install --upgrade pip
          pip install -r reqirements.txt
        
      - name: Run migrations
        run: python manage.py migrate
        
      - name: Run tests
        run: coverage run manage.py test
